#ifndef GPIOTE_H
#define GPIOTE_H
#include <stdint.h>

#define GPIOTE ((NRF_GPIOTE_REG*)0x40006000)

typedef struct {
	volatile uint32_t TASKS_OUT[8];
	volatile uint32_t RESERVED0[4];
	volatile uint32_t TASKS_SET[8];
	volatile uint32_t RESERVED1[4];
	volatile uint32_t TASKS_CLR[8];
	volatile uint32_t RESERVED3[32];
	volatile uint32_t EVENTS_IN[8];
	volatile uint32_t RESERVED4[23];
	volatile uint32_t EVENTS_PORT;
	volatile uint32_t RESERVED5[97];
	volatile uint32_t INTENSET;
	volatile uint32_t INTENCLR;
	volatile uint32_t RESERVED6[129];
	volatile uint32_t CONFIG[8];
} NRF_GPIOTE_REG;

// GPIOTE CONFIG MODE (Bits 1:0)
#define GPIOTE_CONFIG_MODE_POS      0
#define GPIOTE_CONFIG_MODE_MSK      (0x3ul << GPIOTE_CONFIG_MODE_POS)

#define GPIOTE_CONFIG_MODE_DISABLED (0x0ul << GPIOTE_CONFIG_MODE_POS)
#define GPIOTE_CONFIG_MODE_EVENT    (0x1ul << GPIOTE_CONFIG_MODE_POS)
#define GPIOTE_CONFIG_MODE_TASK     (0x3ul << GPIOTE_CONFIG_MODE_POS)

// GPIOTE CONFIG PSEL (Bits 12:8)
#define GPIOTE_CONFIG_PSEL_POS      8
#define GPIOTE_CONFIG_PSEL_MSK      (0x1Ful << GPIOTE_CONFIG_PSEL_POS)

// Shift a pin num into PSEL field
#define GPIOTE_CONFIG_PSEL(pin)     (((pin) << GPIOTE_CONFIG_PSEL_POS) & GPIOTE_CONFIG_PSEL_MSK)

// GPIOTE CONFIG POLARITY (Bits 17:16)
#define GPIOTE_CONFIG_POLARITY_POS      16
#define GPIOTE_CONFIG_POLARITY_MSK      (0x3ul << GPIOTE_CONFIG_POLARITY_POS)

#define GPIOTE_CONFIG_POLARITY_NONE     (0x0 << GPIOTE_CONFIG_POLARITY_POS)
#define GPIOTE_CONFIG_POLARITY_LoToHi   (0x1 << GPIOTE_CONFIG_POLARITY_POS)
#define GPIOTE_CONFIG_POLARITY_HiToLo   (0x2 << GPIOTE_CONFIG_POLARITY_POS)
#define GPIOTE_CONFIG_POLARITY_TOGGLE   (0x3 << GPIOTE_CONFIG_POLARITY_POS)

// GPIOTE CONFIG OUTINIT (Bit 20)
#define GPIOTE_CONFIG_OUTINIT_POS      20
#define GPIOTE_CONFIG_OUTINIT_MSK      (0x1ul << GPIOTE_CONFIG_OUTINIT_POS)

#define GPIOTE_CONFIG_OUTINIT_LO       (0x0 << GPIOTE_CONFIG_OUTINIT_POS)
#define GPIOTE_CONFIG_OUTINIT_HI       (0x1 << GPIOTE_CONFIG_OUTINIT_POS)

#endif
